package com.sn.carpooling.entity;

import java.io.Serializable;
import java.util.Date;

public class LoginRecord implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_record.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_record.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_record.login_type
     *
     * @mbg.generated
     */
    private String loginType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_record.login_ip
     *
     * @mbg.generated
     */
    private String loginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_record.failed_password
     *
     * @mbg.generated
     */
    private String failedPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login_record.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table login_record
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_record.id
     *
     * @return the value of login_record.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_record.id
     *
     * @param id the value for login_record.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_record.open_id
     *
     * @return the value of login_record.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_record.open_id
     *
     * @param openId the value for login_record.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_record.login_type
     *
     * @return the value of login_record.login_type
     *
     * @mbg.generated
     */
    public String getLoginType() {
        return loginType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_record.login_type
     *
     * @param loginType the value for login_record.login_type
     *
     * @mbg.generated
     */
    public void setLoginType(String loginType) {
        this.loginType = loginType == null ? null : loginType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_record.login_ip
     *
     * @return the value of login_record.login_ip
     *
     * @mbg.generated
     */
    public String getLoginIp() {
        return loginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_record.login_ip
     *
     * @param loginIp the value for login_record.login_ip
     *
     * @mbg.generated
     */
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp == null ? null : loginIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_record.failed_password
     *
     * @return the value of login_record.failed_password
     *
     * @mbg.generated
     */
    public String getFailedPassword() {
        return failedPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_record.failed_password
     *
     * @param failedPassword the value for login_record.failed_password
     *
     * @mbg.generated
     */
    public void setFailedPassword(String failedPassword) {
        this.failedPassword = failedPassword == null ? null : failedPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login_record.create_time
     *
     * @return the value of login_record.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login_record.create_time
     *
     * @param createTime the value for login_record.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", openId=").append(openId);
        sb.append(", loginType=").append(loginType);
        sb.append(", loginIp=").append(loginIp);
        sb.append(", failedPassword=").append(failedPassword);
        sb.append(", createTime=").append(createTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}