package com.sn.carpooling.entity;

import java.io.Serializable;
import java.util.Date;

public class WechatUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.open_id
     *
     * @mbg.generated
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.wechat_open_id
     *
     * @mbg.generated
     */
    private String wechatOpenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.wechat_union_id
     *
     * @mbg.generated
     */
    private String wechatUnionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wechat_user.register_time
     *
     * @mbg.generated
     */
    private Date registerTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.id
     *
     * @return the value of wechat_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.id
     *
     * @param id the value for wechat_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.open_id
     *
     * @return the value of wechat_user.open_id
     *
     * @mbg.generated
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.open_id
     *
     * @param openId the value for wechat_user.open_id
     *
     * @mbg.generated
     */
    public void setOpenId(String openId) {
        this.openId = openId == null ? null : openId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.wechat_open_id
     *
     * @return the value of wechat_user.wechat_open_id
     *
     * @mbg.generated
     */
    public String getWechatOpenId() {
        return wechatOpenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.wechat_open_id
     *
     * @param wechatOpenId the value for wechat_user.wechat_open_id
     *
     * @mbg.generated
     */
    public void setWechatOpenId(String wechatOpenId) {
        this.wechatOpenId = wechatOpenId == null ? null : wechatOpenId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.wechat_union_id
     *
     * @return the value of wechat_user.wechat_union_id
     *
     * @mbg.generated
     */
    public String getWechatUnionId() {
        return wechatUnionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.wechat_union_id
     *
     * @param wechatUnionId the value for wechat_user.wechat_union_id
     *
     * @mbg.generated
     */
    public void setWechatUnionId(String wechatUnionId) {
        this.wechatUnionId = wechatUnionId == null ? null : wechatUnionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wechat_user.register_time
     *
     * @return the value of wechat_user.register_time
     *
     * @mbg.generated
     */
    public Date getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wechat_user.register_time
     *
     * @param registerTime the value for wechat_user.register_time
     *
     * @mbg.generated
     */
    public void setRegisterTime(Date registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", openId=").append(openId);
        sb.append(", wechatOpenId=").append(wechatOpenId);
        sb.append(", wechatUnionId=").append(wechatUnionId);
        sb.append(", registerTime=").append(registerTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}