package com.sn.carpooling.dao;

import java.util.List;

public interface LoginRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbg.generated
     */
    int insert(LoginRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbg.generated
     */
    LoginRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbg.generated
     */
    List<LoginRecord> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table login_record
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LoginRecord record);
}